name: Cluster Flow
description: A pipelining tool to automate and standardise bioinformatics analyses on cluster environments
author: Phil Ewels
permalink: pretty
baseurl: ""
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, node_modules, v0.3]
docs_version: 0.3
depreciated: true

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
